version: 2.1

commands:
  restore_cached_workspace:
    steps:
      - attach_workspace:
          at: ~/
      - install-required-node
      - unpack-dependencies
  
  install-required-node:
    # https://discuss.circleci.com/t/switch-nodejs-version-on-machine-executor-solved/26675/2
    description: Install Node version matching .node-version
    steps:
      # installing NVM will use git+ssh, so update known_hosts
      - update_known_hosts
      - run:
          name: Install Node
          command: |
            node_version=$(cat .node-version)
            source ./scripts/ensure-node.sh
            echo "Installing Yarn"
            npm install yarn -g # ensure yarn is installed with the correct node engine
            yarn check-node-version
      - run:
          name: Check Node
          command: |
            source ./scripts/ensure-node.sh
            yarn check-node-version

  unpack-dependencies:
    description: 'Unpacks dependencies associated with the current workflow'
    steps:
      - install_cache_helpers_dependencies
      - run:
          name: Generate Circle Cache Key
          command: node scripts/circle-cache.js --action cacheKey > circle_cache_key
      - run:
          name: Generate platform key
          command: node ./scripts/get-platform-key.js > platform_key
      - restore_cache:
          name: Restore cache state, to check for known modules cache existence
          key: v{{ checksum ".circleci/cache-version.txt" }}-{{ checksum "platform_key" }}-node-modules-cache-{{ checksum "circle_cache_key" }}
      - run:
          name: Move node_modules back from /tmp
          command: |
            if [[ -d "/tmp/node_modules_cache" ]]; then
              mv /tmp/node_modules_cache/root_node_modules ~/cypress/node_modules
              mv /tmp/node_modules_cache/cli_node_modules ~/cypress/cli/node_modules
              mv /tmp/node_modules_cache/system-tests_node_modules ~/cypress/system-tests/node_modules
              mv /tmp/node_modules_cache/globbed_node_modules ~/cypress/globbed_node_modules
              rm -rf /tmp/node_modules_cache
            fi
      - run:
          name: Restore all node_modules to proper workspace folders
          command: node scripts/circle-cache.js --action unpack

jobs:
  binary-release:
    docker:
      - image: cimg/node:current
    steps:
      - restore_cached_workspace
      - run:
          name: Binary Release
          command: |
            echo 'run binary release'

workflows:
  # the setup-workflow workflow is always triggered.
  setup-workflow:
    jobs:
      - binary-release
